version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pnalog-postgres
    env_file:
      - dev.env
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pnalog-postgres-data:/var/lib/postgresql/data

volumes:
  pnalog-postgres-data: