version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pnalog-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pnalog-postgres-data:/var/lib/postgresql/data

volumes:
  pnalog-postgres-data: